version: '3.9'

services:
  traefik:
    image: "traefik:v2.7"
    container_name: "traefik"
    ports:
      - "80:80"
      # (Optional) Expose Dashboard
      - "8080:8080"  # Don't do this in production!
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik
  backend:
    image: backend:v1.0.0
    container_name: backend
    environment:
      - SSE_SERVER_HOST=backend
      - SSE_SERVER_PORT=50052
      - DISPATCHER_HOST=dispatcher
      - DISPATCHER_PORT=50051
    labels:
      - sse-server
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.rule=Host(`localhost`) && PathPrefix(`/`)"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
    ports:
      - "5000:5000"
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik
    depends_on:
      - dispatcher
  dispatcher:
    image: dispatcher:v1.0.0
    container_name: dispatcher
    environment:
      - HOST=dispatcher
      - PORT=50051
      - DOCKER_NETWORK=traefik
      - DOCKER_SSE_SERVER_LABEL=sse-server
      - DOCKER_SSE_SERVER_PORT=50052
    labels:
      - dispatcher-server
    ports:
      - "50051:50051"
    volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
       - traefik
networks:
  traefik:
    name: traefik
    driver: bridge

